<?php

use App\Http\Controllers\Admin\AreaNoodleController;
use App\Http\Controllers\Admin\Calculate\PurchasePriceController;
use App\Http\Controllers\Calculate\MatchingController;
use App\Http\Controllers\Calculate\VolumeNoodleController as CalculateVolumeNoodleController;
use App\Http\Controllers\Admin\Calculate\UnitCostPriceController;
use App\Http\Controllers\Admin\Entry\RmPriceController;
use App\Http\Controllers\Admin\Entry\VolumeNoodleController;
use App\Http\Controllers\Admin\FactoryController;
use App\Http\Controllers\Admin\FinishedGoodController;
use App\Http\Controllers\Admin\Formula\FormulaFgController;
use App\Http\Controllers\Admin\Formula\FormulaNdlController;
use App\Http\Controllers\Admin\NoodleController;
use App\Http\Controllers\Admin\RawMaterialController;
use App\Http\Controllers\Admin\ReferenceController;
use App\Http\Controllers\Admin\SynonimController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\FirstPasswordController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LocaleController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->name('login.store');
});

Route::middleware('auth')->group(function () {
    Route::get('/buat-password', [FirstPasswordController::class, 'edit'])->name('password.first.edit');
    Route::put('/buat-password', [FirstPasswordController::class, 'update'])->name('password.first.update');
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

    Route::middleware('password.changed')->group(function () {
        Route::get('/locale/{locale}', [LocaleController::class, 'switch'])->name('locale.switch');

        Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
        Route::get('/calendar', fn () => view('pages.calender', ['title' => 'Calendar']))->name('calendar');
        Route::get('/profile', fn () => view('pages.profile', ['title' => 'Profile']))->name('profile');
        Route::get('/form-elements', fn () => view('pages.form.form-elements', ['title' => 'Form Elements']))->name('form-elements');
        Route::get('/basic-tables', fn () => view('pages.tables.basic-tables', ['title' => 'Basic Tables']))->name('basic-tables');
        Route::get('/blank', fn () => view('pages.blank', ['title' => 'Blank']))->name('blank');
        Route::get('/error-404', fn () => view('pages.errors.error-404', ['title' => 'Error 404']))->name('error-404');
        Route::get('/line-chart', fn () => view('pages.chart.line-chart', ['title' => 'Line Chart']))->name('line-chart');
        Route::get('/bar-chart', fn () => view('pages.chart.bar-chart', ['title' => 'Bar Chart']))->name('bar-chart');
        Route::get('/alerts', fn () => view('pages.ui-elements.alerts', ['title' => 'Alerts']))->name('alerts');
        Route::get('/avatars', fn () => view('pages.ui-elements.avatars', ['title' => 'Avatars']))->name('avatars');
        Route::get('/badge', fn () => view('pages.ui-elements.badges', ['title' => 'Badges']))->name('badges');
        Route::get('/buttons', fn () => view('pages.ui-elements.buttons', ['title' => 'Buttons']))->name('buttons');
        Route::get('/image', fn () => view('pages.ui-elements.images', ['title' => 'Images']))->name('images');
        Route::get('/videos', fn () => view('pages.ui-elements.videos', ['title' => 'Videos']))->name('videos');

        Route::middleware('superadmin')->prefix('admin')->name('admin.')->group(function () {
            Route::get('/users', [UserController::class, 'index'])->name('users.index');
            Route::post('/users', [UserController::class, 'store'])->name('users.store');
            Route::put('/users/{user}', [UserController::class, 'update'])->name('users.update');
            Route::patch('/users/{user}/toggle-status', [UserController::class, 'toggleStatus'])->name('users.toggle-status');
            Route::patch('/users/{user}/reset-password', [UserController::class, 'resetPassword'])->name('users.reset-password');
            Route::get('/maintenance/noodle/noodle', [NoodleController::class, 'index'])->name('maintenance.noodle.index');
            Route::get('/maintenance/noodle/data', [NoodleController::class, 'data'])->name('maintenance.noodle.data');
            Route::get('/maintenance/noodle/noodle/create', [NoodleController::class, 'create'])->name('maintenance.noodle.create');
            Route::post('/maintenance/noodle', [NoodleController::class, 'store'])->name('maintenance.noodle.store');
            Route::put('/maintenance/noodle/{noodle}', [NoodleController::class, 'update'])->name('maintenance.noodle.update');
            Route::delete('/maintenance/noodle/{noodle}', [NoodleController::class, 'destroy'])->name('maintenance.noodle.destroy');
            Route::get('/maintenance/area-noodle', [AreaNoodleController::class, 'index'])->name('maintenance.area-noodle.index');
            Route::get('/maintenance/area-noodle/data', [AreaNoodleController::class, 'data'])->name('maintenance.area-noodle.data');
            Route::get('/maintenance/area-noodle/create', [AreaNoodleController::class, 'create'])->name('maintenance.area-noodle.create');
            Route::post('/maintenance/area-noodle', [AreaNoodleController::class, 'store'])->name('maintenance.area-noodle.store');
            Route::put('/maintenance/area-noodle/{areaNoodle}', [AreaNoodleController::class, 'update'])->name('maintenance.area-noodle.update');
            Route::delete('/maintenance/area-noodle/{areaNoodle}', [AreaNoodleController::class, 'destroy'])->name('maintenance.area-noodle.destroy');
            Route::get('/maintenance/finished-good', [FinishedGoodController::class, 'index'])->name('maintenance.finished-good.index');
            Route::get('/maintenance/finished-good/data', [FinishedGoodController::class, 'data'])->name('maintenance.finished-good.data');
            Route::get('/maintenance/finished-good/create', [FinishedGoodController::class, 'create'])->name('maintenance.finished-good.create');
            Route::post('/maintenance/finished-good', [FinishedGoodController::class, 'store'])->name('maintenance.finished-good.store');
            Route::get('/maintenance/finished-good/{finishedGood}/edit', [FinishedGoodController::class, 'edit'])->name('maintenance.finished-good.edit');
            Route::put('/maintenance/finished-good/{finishedGood}', [FinishedGoodController::class, 'update'])->name('maintenance.finished-good.update');
            Route::delete('/maintenance/finished-good/{finishedGood}', [FinishedGoodController::class, 'destroy'])->name('maintenance.finished-good.destroy');
            Route::get('/maintenance/raw-material', [RawMaterialController::class, 'index'])->name('maintenance.raw-material.index');
            Route::get('/maintenance/raw-material/data', [RawMaterialController::class, 'data'])->name('maintenance.raw-material.data');
            Route::get('/maintenance/raw-material/create', [RawMaterialController::class, 'create'])->name('maintenance.raw-material.create');
            Route::post('/maintenance/raw-material', [RawMaterialController::class, 'store'])->name('maintenance.raw-material.store');
            Route::get('/maintenance/raw-material/{rawMaterial}/edit', [RawMaterialController::class, 'edit'])->name('maintenance.raw-material.edit');
            Route::put('/maintenance/raw-material/{rawMaterial}', [RawMaterialController::class, 'update'])->name('maintenance.raw-material.update');
            Route::delete('/maintenance/raw-material/{rawMaterial}', [RawMaterialController::class, 'destroy'])->name('maintenance.raw-material.destroy');
            Route::get('/maintenance/formula/ndl', [FormulaNdlController::class, 'index'])->name('maintenance.formula.ndl');
            Route::get('/maintenance/formula/ndl/data', [FormulaNdlController::class, 'show'])->name('maintenance.formula.ndl.data');
            Route::put('/maintenance/formula/ndl/{noodle}', [FormulaNdlController::class, 'update'])->name('maintenance.formula.ndl.update');
            Route::get('/maintenance/formula/fg', [FormulaFgController::class, 'index'])->name('maintenance.formula.fg');
            Route::get('/maintenance/formula/fg/data', [FormulaFgController::class, 'show'])->name('maintenance.formula.fg.data');
            Route::put('/maintenance/formula/fg/{finishedGood}', [FormulaFgController::class, 'update'])->name('maintenance.formula.fg.update');
            Route::get('/maintenance/reference', [ReferenceController::class, 'index'])->name('maintenance.reference.index');
            Route::get('/maintenance/reference/data', [ReferenceController::class, 'data'])->name('maintenance.reference.data');
            Route::get('/maintenance/reference/create', [ReferenceController::class, 'create'])->name('maintenance.reference.create');
            Route::post('/maintenance/reference', [ReferenceController::class, 'store'])->name('maintenance.reference.store');
            Route::get('/maintenance/reference/{reference}/edit', [ReferenceController::class, 'edit'])->name('maintenance.reference.edit');
            Route::put('/maintenance/reference/{reference}', [ReferenceController::class, 'update'])->name('maintenance.reference.update');
            Route::delete('/maintenance/reference/{reference}', [ReferenceController::class, 'destroy'])->name('maintenance.reference.destroy');
            Route::get('/maintenance/factory', [FactoryController::class, 'index'])->name('maintenance.factory.index');
            Route::get('/maintenance/factory/data', [FactoryController::class, 'data'])->name('maintenance.factory.data');
            Route::get('/maintenance/factory/create', [FactoryController::class, 'create'])->name('maintenance.factory.create');
            Route::post('/maintenance/factory', [FactoryController::class, 'store'])->name('maintenance.factory.store');
            Route::get('/maintenance/factory/{factory}/edit', [FactoryController::class, 'edit'])->name('maintenance.factory.edit');
            Route::put('/maintenance/factory/{factory}', [FactoryController::class, 'update'])->name('maintenance.factory.update');
            Route::delete('/maintenance/factory/{factory}', [FactoryController::class, 'destroy'])->name('maintenance.factory.destroy');
            Route::get('/maintenance/synonim', [SynonimController::class, 'index'])->name('maintenance.synonim.index');
            Route::get('/maintenance/synonim/data', [SynonimController::class, 'data'])->name('maintenance.synonim.data');
            Route::get('/maintenance/synonim/create', [SynonimController::class, 'create'])->name('maintenance.synonim.create');
            Route::post('/maintenance/synonim', [SynonimController::class, 'store'])->name('maintenance.synonim.store');
            Route::put('/maintenance/synonim/{synonim}', [SynonimController::class, 'update'])->name('maintenance.synonim.update');
            Route::delete('/maintenance/synonim/{synonim}', [SynonimController::class, 'destroy'])->name('maintenance.synonim.destroy');
            Route::get('/entry/volume-noodle', [VolumeNoodleController::class, 'index'])->name('entry.volume-noodle.index');
            Route::get('/entry/volume-noodle/data', [VolumeNoodleController::class, 'data'])->name('entry.volume-noodle.data');
            Route::get('/entry/volume-noodle/create', [VolumeNoodleController::class, 'create'])->name('entry.volume-noodle.create');
            Route::post('/entry/volume-noodle', [VolumeNoodleController::class, 'store'])->name('entry.volume-noodle.store');
            Route::put('/entry/volume-noodle/{volumeNoodle}', [VolumeNoodleController::class, 'update'])->name('entry.volume-noodle.update');
            Route::delete('/entry/volume-noodle/{volumeNoodle}', [VolumeNoodleController::class, 'destroy'])->name('entry.volume-noodle.destroy');
            Route::get('/entry/rm-price', [RmPriceController::class, 'index'])->name('entry.rm-price.index');
            Route::get('/entry/rm-price/data/{rawMaterial}', [RmPriceController::class, 'show'])->name('entry.rm-price.data');
            Route::post('/entry/rm-price', [RmPriceController::class, 'store'])->name('entry.rm-price.store');
            Route::get('/calculate/purchase-price', [PurchasePriceController::class, 'index'])->name('calculate.purchase-price.index');
            Route::get('/calculate/volume-noodle', [CalculateVolumeNoodleController::class, 'index'])->name('calculate.volume-noodle.index');
            Route::post('/calculate/volume-noodle', [CalculateVolumeNoodleController::class, 'store'])->name('calculate.volume-noodle.store');
            Route::get('/calculate/volume-noodle/inputs', [CalculateVolumeNoodleController::class, 'inputs'])->name('calculate.volume-noodle.inputs');
            Route::get('/calculate/matching-price', [MatchingController::class, 'index'])->name('calculate.matching-price.index');
            Route::post('/calculate/matching-price', [MatchingController::class, 'store'])->name('calculate.matching-price.store');
            Route::post('/calculate/purchase-price', [PurchasePriceController::class, 'store'])->name('calculate.purchase-price.store');
            Route::get('/calculate/unit-cost-price', [UnitCostPriceController::class, 'index'])->name('calculate.unit-cost-price.index');
            Route::get('/calculate/unit-cost-price/data', [UnitCostPriceController::class, 'data'])->name('calculate.unit-cost-price.data');
            Route::post('/calculate/unit-cost-price', [UnitCostPriceController::class, 'store'])->name('calculate.unit-cost-price.store');
        });
    });
});

Route::redirect('/signin', '/login');
